config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  get '/search', to: 'search#index'

  resources :jobs, only: :show
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
# frozen_string_literal: true

class Job < ApplicationRecord
  CACHE_JOB_KEY = 'cached_job_search'
  EXPIRE_CACHE = 5.minutes
  STORE_LIMIT = 10_000

  scope :latest, -> { order(published_at: :desc).limit(5) }
  scope :trending, -> { order(updated_at: :asc).limit(5) }

  # api returns id of cached jobs
  def self.search_cache(search_key)
    $redis.lrange(CACHE_JOB_KEY, 0, -1).map do |cache|
      c = JSON.parse(cache)
      c if c['search_key'] == search_key && c['expire_at'] > Time.now.to_i
    end.compact.pluck('job_ids').flatten.uniq
  end

  def self.import(jobs:, user_id:, key:)
    unless jobs.blank?
      # add to cache
      upsert_all(jobs)
      job_ids = jobs.pluck(:guid)
      cache = { search_key: key, job_ids: job_ids, expire_at: EXPIRE_CACHE.from_now.to_i }
      $redis.lpush(CACHE_JOB_KEY, cache.to_json)
      $redis.ltrim(CACHE_JOB_KEY, 0, STORE_LIMIT - 1)
    end
    # broadcast to homepage
    broadcast_to_jobs(jobs: jobs, user_id: user_id)
  end

  def self.broadcast_to_jobs(jobs:, user_id:)
    ActionCable.server.broadcast "jobs_#{user_id}", { jobs: jobs }
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :set_user_id

  private

  # set unique identifier to user
  def set_user_id
    @user_id = cookies.encrypted[:current_user] ||= session.id.to_s
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  # GET /
  def index
    @trending = Job.trending
    @latest = Job.latest
  end
end

app/controllers/jobs_controller.rb
# frozen_string_literal: true

class JobsController < ApplicationController
  # GET /jobs/:id
  def show
    @job = Job.find_by(guid: params[:id])
  end
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  # GET /search
  # GET /search.json
  def index
    # check in cached jobs
    cached_job_ids = Job.search_cache(params[:query])
    if cached_job_ids.present?
      @jobs = Job.where(guid: cached_job_ids)
    else
      SearchJob.perform_later(key: params[:query], user_id: @user_id)
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/jobs_helper.rb
# frozen_string_literal: true

module JobsHelper
  require 'digest/md5'

  def job_image(title)
    color = Digest::MD5.hexdigest(title)[0..5]
    "https://dummyimage.com/300x300/#{color}/ffffff.png&text=#{title.scan(/\w+/)[0..1].join(' ').capitalize}"
  end

  def extract_text(html)
    ActionView::Base.full_sanitizer.sanitize(html)
  end

  def format_date(date)
    return 'Date not available' if date.blank?

    date.strftime('%B %d, %Y %H:%M %p')
  end
end

app/views/home/index.html.erb
<%= react_component("Search") %>
<%= render partial: "jobs/job_cards", locals: { name: "Trending Jobs", job_list: @trending } unless @trending.blank? %>
<%= render partial: "jobs/job_cards", locals: { name: "Latest Jobs", job_list: @latest } unless @latest.blank? %>

app/views/jobs/_job_cards.html.erb
<h1 class="header"><%= name %></h1>
<div class="ui divider"></div>
<div class="ui link cards app-cards">
  <% job_list.each do |job| %>
    <a class="card" href="<%= job_path(job.guid) %>">
      <div class="image">
        <img src="<%= job_image(job.title) %>">
      </div>
      <div class="content">
        <div class="header"><%= job.title %></div>
        <div class="meta"><%= job.author %></div>
        <div class="description"><%= truncate extract_text(job.description), length: 200, seperator: /\w+/ %></div>
      </div>
      <div class="extra content">
        <span class="right floated">
          <i class="star icon"></i> <%= rand(5) %>
        </span>
        <span>
          Applicants: <%= number_to_human rand(100) %>
        </span>
      </div>
    </a>
  <% end %>
</div>

app/views/jobs/show.html.erb
<div class="ui padded raised segment">
  <div class="ui items">
    <div class="item">
      <div class="image">
        <img src="<%= job_image(@job.title) %>">
      </div>
      <div class="content">
        <h1 class="header"><%= @job.title %></h1>
        <div class="meta">
          <span class="cinema"><%= @job.author %></span>
        </div>
        <div class="meta">
          <span class="version">Applicants <%= rand(100) %></span>
        </div>
        <div class="meta">
          <span class="release">Published <%= format_date @job.published_at %></span>
        </div>
        <div class="bottom aligned content">
          <a class="ui primary button" href="<%= @job.link %>">Apply</a>
        </div>
      </div>
    </div>
  </div>
  <div class="ui divider"></div>
  <div class="ui three small statistics">
    <div class="statistic">
      <div class="value">
        <%= number_to_human rand(100) %>
      </div>
      <div class="label">
        Applicants
      </div>
    </div>
    <div class="statistic">
      <div class="value">
        <i class="small yellow star icon"></i> <%= rand(5) %>
      </div>
      <div class="label">
        Stars
      </div>
    </div>
    <div class="statistic">
      <div class="value">
        <i class="small users icon"></i> <%= number_with_delimiter rand(1000) %>
      </div>
      <div class="label">
        Ratings
      </div>
    </div>
  </div>
  <div class="ui divider"></div>
  <h2 class="header">Description</h2>
  <div>
    <p><%= @job.description.html_safe %></p>
  </div>
  <div class="ui divider"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobFinder</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui container">
      <div class="ui stackable menu">
        <a class="header item" href="/">
          <img src="/logo.png">
          <span style="margin-left: 8px;">JobFinder</span>
        </a>
        <a class="item" href="/">Home</a>
        <a class="disabled item">Careers</a>
        <a class="disabled item">Companies</a>
        <div class="right menu">
          <div class="item">
            <div class="ui secondary disabled button">Log In</div>
          </div>
          <div class="item">
            <div class="ui primary disabled button">Sign Up</div>
          </div>
        </div>
      </div>
    </div>
    <div class="ui container content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/search/index.html.erb
<div class="ui raised segment">
  <h1 class="ui header" id="total_results"><%= params[:query] %> (<%= @jobs&.size.to_i %> results)</h1>  
  <div class="ui divider"></div>
  <div class="ui divided link items" id="result_page">
    <% if  @jobs.blank? %>
      <div class="ui active inverted dimmer" style='min-height: 400px;'>
        <div class="ui text loader">Request is being processed and results will be available shortly.</div>
      </div>
    <% else %>
      <% @jobs.each do |job| %>
        <a class="item" href="<%= job_path(job.guid) %>">
          <div class="small image">
            <img src="<%= job_image(job.title) %>">
          </div>
          <div class="content">
            <div class="header"><%= job.title %></div>
            <div class="meta">
              <span><%= job.author["name"] %></span>
            </div>
            <div class="description">
              <p><%= truncate extract_text(job.description), length: 200, seperator: /\w+/ %></p>
            </div>
            <div class="extra">
              <div class="ui right floated primary button">
                View More
                <i class="right chevron icon"></i>
              </div>
              <div class="ui label"><i class="green arrow alternate circle down outline icon"></i> <%= number_to_human rand(100) %> Applicants</div>
              <div class="ui label"><i class="yellow star icon"></i> <%= rand(5) %> Rating</div>
            </div>
          </div>
        </a>
      <% end %>
    <% end %>
  </div>
</div>